### ISSUE TITLE
怎样可以在工作流初始的时候增加sass编译选项？

### ISSUE THREAD

**Issue by Mrlilili** [weixin/generator-workflow#2]
现在我可以在初始化后的项目的TaskBuildDev.js中增添sass功能，但是每次都要去覆盖原本初始生成的TaskXXX.js，有什么办法可以直接在初始化的时候把sass的功能加进去。算是对这个generator进行二次开发吧？

**Comment by hzlzh** [comment]
两种方法：
方法1：你可以直接修改 https://github.com/weixin/generator-workflow/blob/master/app/templates/_tasks/TaskBuildDev.js 中的文件内容之后重命名整个目录为 `generator-workflow-xxx`，然后在 ./generator-workflow-xxx 下执行 `npm link` 这样以后使用 `yo workflow-xxx` 初始化就好了，同时原来的命令会保留不受影响。
方法2：checkout 一份 `generator-workflow` 到本地，然后修改完毕之后直接 `npm link` 这样以后执行 `yo workflow` 的时候会用你修改过的新版本。
