### ISSUE TITLE
yo workflow时出现如下错误

### ISSUE THREAD

**Issue by guohui8** [weixin/generator-workflow#3]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\n                     ode_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: w                     anted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN project-test@0.0.1 No description
npm WARN project-test@0.0.1 No repository field.
npm WARN project-test@0.0.1 No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_mod                     ules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-lwip@0.1.3 install: `node prebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-lwip@0.1.3 install script 'node prebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-lwip package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node prebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-lwip
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-lwip
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Guohui\Desktop\node.js\npm-debug.log
fs.js:952
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\Guohui\Desktop\node.js\node_                     modules\node-sass\vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:952:18)
    at Object.getInstalledBinaries (C:\Users\Guohui\Desktop\node.js\node_modules\node-sa                     ss\lib\extensions.js:121:13)
    at foundBinariesList (C:\Users\Guohui\Desktop\node.js\node_modules\node-sass\lib\err                     ors.js:20:15)
    at foundBinaries (C:\Users\Guohui\Desktop\node.js\node_modules\node-sass\lib\errors.                     js:15:5)
    at Object.module.exports.missingBinary (C:\Users\Guohui\Desktop\node.js\node_modules                     \node-sass\lib\errors.js:45:5)
    at module.exports (C:\Users\Guohui\Desktop\node.js\node_modules\node-sass\lib\bindin                     g.js:15:30)
    at Object.<anonymous> (C:\Users\Guohui\Desktop\node.js\node_modules\node-sass\lib\in                     dex.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

**Comment by hzlzh** [comment]
看起来是 node-sass 没有安装好的问题。
如果是用 cnpm 安装的的，尝试一下用 npm 重新安装呢。

**Comment by guohui8** [comment]
用npm重新安装的，还是会出错额。
------------------------------------------------------------------------------
Guohui@GuohuiPC MINGW64 ~/Desktop/generator-workflow
$ yo workflow

     _-----_
    |       |
    |--(o)--|   .------------------------------------------------.
   `---------´  |    Welcome to tmt-workflow Yeoman generator,   |
    ( _´U`_ )   |       More configs in `.tmtworkflowrc`      |
    /___A___\   '________________________________________________'
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

开始配置工作流:`
? 项目名:  (project-xxx) GuohuiTest
? 项目名:  GuohuiTest
? 版本号:  (0.0.1)
? 版本号:  0.0.1
? 作者:  () Guohui
? 作者:  Guohui
? ▬▬▬▬ 选择更多功能 <空格键> ▬▬▬▬ (Press <space> to select, <a> to toggle all, <i> to in
? ▬▬▬▬ 选择更多功能 <空格键> ▬▬▬▬ 开启: LiveReload               // 文件变动触发浏览器自动刷新
? 配置完成, 项目创建成功!
? 配置完成, 项目创建成功!
  是否自动执行 `npm install & gulp build_dev` ? Yes
GuohuiTest
   create GuohuiTest\gulpfile.js
   create GuohuiTest\src\css\header.less
   create GuohuiTest\src\css\lib-mixins.less
   create GuohuiTest\src\css\lib-rem.less
   create GuohuiTest\src\css\lib-reset.less
   create GuohuiTest\src\css\style-index.less
   create GuohuiTest\src\css\tips.less
   create GuohuiTest\src\html\index.html
   create GuohuiTest\src\img\bg-body.png
   create GuohuiTest\src\img\bg-logo.png
   create GuohuiTest\src\slice\icon-dribbble.png
   create GuohuiTest\src\slice\icon-dribbble@2x.png
   create GuohuiTest\src\slice\icon-facebook.png
   create GuohuiTest\src\slice\icon-facebook@2x.png
   create GuohuiTest\src\slice\icon-github.png
   create GuohuiTest\src\slice\icon-github@2x.png
   create GuohuiTest\src\slice\icon-instagram.png
   create GuohuiTest\src\slice\icon-instagram@2x.png
   create GuohuiTest\src\slice\icon-twitter.png
   create GuohuiTest\src\slice\icon-twitter@2x.png
   create _tasks\TaskBuildDev.js
   create _tasks\TaskBuildDist.js
   create _tasks\TaskFTP.js
   create _tasks\TaskSFTP.js
   create _tasks\TaskZip.js
   create _tasks\common\changed.js
   create _tasks\common\webp.js
   create _tasks\index.js
   create _tasks\lib\util.js
   create _tasks\plugins\TmTIndex.js
   create _tasks\plugins\ftp.js
   create .tmtworkflowrc
   create package.json


I'm all done. Running npm install for you to install the required dependencies. If this fails, try running the command yourself.



> node-lwip@0.1.3 install C:\Users\Guohui\Desktop\generator-workflow\node_modules\gulp-tmtsprite\node_modules\node-lwip
> node prebuild

{ node: '6.10.1', modules: '48' }
Your node version is out of date, please install the latest one!

C:\Users\Guohui\Desktop\generator-workflow\node_modules\gulp-tmtsprite\node_modules\node-lwip>if not defined npm_config_node_gyp (
node "C:\Users\Guohui\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )

gyp

ERR!
 clean error

gyp
 ERR! stack Error: EPERM: operation not permitted, unlink 'C:\Users\Guohui\Desktop\generator-workflow\node_modules\gulp-tmtsprite\node_modules\node-lwip\build\Release\lwip_decoder.node'
gyp ERR! stack
     at Error (native)

gyp
 ERR! System Windows_NT 10.0.14393

gyp
 ERR! command "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Guohui\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"

gyp ERR!
 cwd C:\Users\Guohui\Desktop\generator-workflow\node_modules\gulp-tmtsprite\node_modules\node-lwip

gyp ERR! node -v
 v6.10.1

gyp
 ERR! node-gyp -v v3.6.2

gyp

ERR!

not ok

child process exited with code 1
C:\Users\Guohui\Desktop\generator-workflow\node_modules\gulp-tmtsprite\node_modules\node-lwip\prebuild.js:123
        if (err) throw err;
                 ^

Error: Command failed: node-gyp rebuild
gyp ERR! clean error
gyp ERR! stack Error: EPERM: operation not permitted, unlink 'C:\Users\Guohui\Desktop\generator-workflow\node_modules\gulp-tmtsprite\node_modules\node-lwip\build\Release\lwip_decoder.node'
gyp ERR! stack     at Error (native)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Guohui\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Guohui\Desktop\generator-workflow\node_modules\gulp-tmtsprite\node_modules\node-lwip
gyp ERR! node -v v6.10.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm WARN guohuitest@0.0.1 No description
npm WARN guohuitest@0.0.1 No repository field.
npm WARN guohuitest@0.0.1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-lwip@0.1.3 install: `node prebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-lwip@0.1.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Program Files\nodejs\node_cache\_logs\2017-06-19T10_54_35_743Z-debug.log
module.js:471
    throw err;
    ^

Error: Cannot find module 'gulp-tmtsprite'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Guohui\Desktop\generator-workflow\_tasks\TaskBuildDist.js:15:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

Guohui@GuohuiPC MINGW64 ~/Desktop/generator-workflow
$

**Comment by hzlzh** [comment]
node-gyp 安装失败，还是网络问题，是否在爬墙状态，用一下代理试试

**Comment by guohui8** [comment]
额，应该不是网络问题，代理试了也不行，错误和上面差不多。
lwip没法装，node-gyp build没法执行。
https://github.com/nodejs/node-gyp#installation
 看了下，因为是win10 x64的，应该是需要安装Python和windows-build-tools，但刚试了也不行，快要崩溃了呜呜~
我还是用客户端的方式方便点吧，多谢啦！

**Comment by hzlzh** [comment]
多谢反馈，这个问题我们收集并标记了，有进展会给你反馈。
